### ISSUE TITLE
Java heap space out of memory error

### ISSUE THREAD

**Issue by Ines-Filipa** [bio-ontology-research-group/onto2vec#6]
When I run groovy OntoProcess.groovy to get the classes and axioms of the GO ontology, I get the error  java.lang.OutOfMemoryError: Java heap space. Is it a configuration problem or what can I do to avoid this?

**Comment by leechuck** [comment]
Hello. You may want to increase your heap space to avoid this error; you can set an environment variable using `export JAVA_OPTS="-Xmx20g"` or so to set heap space to 20GB, or use `JAVA_OPTS="-Xmx20g" groovy OntoProcess.groovy` to run the Groovy script.

**Comment by Ines-Filipa** [comment]
Thanks for the tip, 1GB was enough.
